# Generated by Django 5.2.7 on 2025-12-13 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Nom du fournisseur')),
                ('expense_type', models.CharField(choices=[('stock', 'Stock'), ('energy', 'Énergie'), ('rent', 'Loyer'), ('salary', 'Salaire'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de dépense')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant ($)')),
                ('expense_date', models.DateField(verbose_name='Date de dépense')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('paid', 'Payée'), ('pending', 'En attente'), ('overdue', 'En retard')], default='pending', max_length=20, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT ($)')),
                ('tps', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TPS (5%)')),
                ('tvq', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TVQ (9.975%)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC ($)')),
                ('invoice_date', models.DateField(verbose_name='Date de facturation')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('paid', 'Payée'), ('pending', 'En attente'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('flow_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=10, verbose_name='Type de flux')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant ($)')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('flow_date', models.DateField(verbose_name='Date du flux')),
                ('related_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='finances.expense', verbose_name='Dépense liée')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows', to='finances.invoice', verbose_name='Facture liée')),
            ],
            options={
                'verbose_name': 'Flux de trésorerie',
                'verbose_name_plural': 'Flux de trésorerie',
                'ordering': ['-flow_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire ($)')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total ligne ($)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finances.invoice', verbose_name='Facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_items', to='stocks.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['invoice', 'id'],
            },
        ),
    ]
