# Generated by Django 5.0.14 on 2025-12-15 22:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Par défaut', max_length=50, unique=True, verbose_name='Profil')),
                ('tps_rate', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5, verbose_name='TPS (taux)')),
                ('tvq_rate', models.DecimalField(decimal_places=4, default=Decimal('0.09975'), max_digits=5, verbose_name='TVQ (taux)')),
            ],
            options={
                'verbose_name': 'Paramètre fiscal',
                'verbose_name_plural': 'Paramètres fiscaux',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé ($)')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('method', models.CharField(choices=[('card', 'Carte'), ('transfer', 'Virement'), ('cash', 'Comptant'), ('other', 'Autre')], default='card', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finances.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
