# Generated by Django 5.0.14 on 2025-12-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_taxconfig_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='TaxConfig',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
