# Generated by Django 5.2.7 on 2025-12-13 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('client_type', models.CharField(choices=[('individual', 'Individuel'), ('company', 'Entreprise'), ('partner', 'Partenaire')], default='individual', max_length=20, verbose_name='Type de client')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20, verbose_name='Statut')),
                ('loyalty_score', models.PositiveIntegerField(default=3, help_text='Note de 1 à 5', verbose_name='Score de fidélité (1-5)')),
                ('satisfaction_score', models.PositiveIntegerField(default=0, help_text='Pourcentage de satisfaction', verbose_name='Score de satisfaction (%)')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Nombre total de commandes')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total dépensé ($)')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Dernière activité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('activity_type', models.CharField(choices=[('visit', 'Visite du site'), ('page_view', 'Consultation de page'), ('order', 'Commande'), ('email', 'Courriel'), ('call', 'Appel téléphonique'), ('document', 'Document (PDF, soumission)'), ('other', 'Autre')], max_length=20, verbose_name="Type d'activité")),
                ('description', models.TextField(verbose_name='Description')),
                ('page_url', models.URLField(blank=True, verbose_name='URL de la page')),
                ('document', models.FileField(blank=True, null=True, upload_to='client_documents/', verbose_name='Document')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='clients.client', verbose_name='Client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': "Journal d'activité client",
                'verbose_name_plural': "Journaux d'activité clients",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('interaction_type', models.CharField(choices=[('call', 'Appel téléphonique'), ('email', 'Email'), ('message', 'Message'), ('meeting', 'Réunion'), ('other', 'Autre')], max_length=20, verbose_name="Type d'interaction")),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('description', models.TextField(verbose_name='Description')),
                ('interaction_date', models.DateTimeField(verbose_name="Date de l'interaction")),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='Utilisateur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Interaction client',
                'verbose_name_plural': 'Interactions clients',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('order_date', models.DateField(verbose_name='Date de commande')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total ($)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('received', 'Réception'), ('preparing', 'Préparation'), ('shipped', 'Expédiée'), ('invoiced', 'Facturée'), ('paid', 'Payée/fermée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande client',
                'verbose_name_plural': 'Commandes clients',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire ($)')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total ligne ($)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='clients.clientorder', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_line_items', to='stocks.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('rating', models.PositiveIntegerField(help_text='Note de satisfaction de 1 à 5 étoiles', verbose_name='Note (1-5 étoiles)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='clients.clientorder', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Évaluation de commande',
                'verbose_name_plural': 'Évaluations de commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire ($)')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clients.cart', verbose_name='Panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stocks.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de panier',
                'verbose_name_plural': 'Articles de panier',
                'ordering': ['cart', 'id'],
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
