# Generated by Django 5.1.3 on 2025-11-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Fournisseur')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code fournisseur')),
                ('default_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise fournisseur (%)')),
                ('delivery_delay_days', models.PositiveIntegerField(default=0, verbose_name='Délai de livraison (jours)')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Coût d'achat ($)")),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente ($)')),
                ('gross_margin_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marge brute (%)')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('reorder_threshold', models.PositiveIntegerField(default=0, verbose_name='Seuil de réapprovisionnement')),
                ('safety_stock', models.PositiveIntegerField(default=0, verbose_name='Stock minimum de sécurité')),
                ('supplier_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise fournisseur (%)')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Poids (kg)')),
                ('stock_entry_date', models.DateField(verbose_name="Date d'entrée en stock")),
                ('warehouse_location', models.CharField(max_length=20, verbose_name='Emplacement entrepôt')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20, verbose_name='Statut produit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pgi.productcategory', verbose_name='Catégorie')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pgi.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['sku'],
            },
        ),
    ]
