# Generated by Django 5.2.7 on 2025-12-13 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Fournisseur')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code fournisseur')),
                ('default_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise fournisseur (%)')),
                ('delivery_delay_days', models.PositiveIntegerField(default=0, verbose_name='Délai de livraison (jours)')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Photo')),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Coût d'achat ($)")),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente ($)')),
                ('gross_margin_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marge brute (%)')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('reorder_threshold', models.PositiveIntegerField(default=0, verbose_name='Seuil de réapprovisionnement')),
                ('safety_stock', models.PositiveIntegerField(default=0, verbose_name='Stock minimum de sécurité')),
                ('supplier_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise fournisseur (%)')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Poids (kg)')),
                ('stock_entry_date', models.DateField(verbose_name="Date d'entrée en stock")),
                ('warehouse_location', models.CharField(max_length=20, verbose_name='Emplacement entrepôt')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=20, verbose_name='Statut produit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stocks.productcategory', verbose_name='Catégorie')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stocks.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=10, verbose_name='Type de mouvement')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Raison')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stocks.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
